[memorization]
# For vocabularies that have not been presented to the user yet, you
# can enable a memorization round where both the query and answer are
# shown.
do_memorization_round = true
memorization_reversed = false

[validation]
# The maximum edit distance for a word to be considered correct
error_tolerance = 2
# For words with a length of less than this, the error tolerance is set to 0
tolerance_min_length = 5

[deck_config]
# The interval of each deck. Must be either a number, representing the 
# duration in days or a string in the format "(<number><unit>)*" 
# (e.g. "1d", "1d2h3m5s")
deck_intervals = [0, "12h", 1, 7, 14, 30, 60, 90, 180, 365]
# Whether the deck numbers should be changed when in ignore-date mode
change_deck_in_ignore_date = false

[keybindings]
skip = 's'
accept_anyway = 'a'
reject_anyway = 'r'
force_quit = 'Q'
save_and_quit = 'w'
edit_mode = 'i'
help = 'h'

[special_letters]
de = [
    { base = "a", special = ["Ä", "ä"] }, 
    { base = "o", special = ["Ö", "ö"] },
    { base = "u", special = ["Ü", "ü"] },
    { base = "s", special = ["ẞ", "ß"] },
]
it = [
    { base = "a", special = ["À", "à"] },
    { base = "e", special = ["É", "é", "È", "è"] },
    { base = "i", special = ["Ì", "ì"] },
    { base = "o", special = ["Ò", "ò"] },
    { base = "u", special = ["Ù", "ù"] },
]
fr = [
    { base = "a", special = ["À", "à", "Â", "â", "Æ", "æ"] },
    { base = "c", special = ["Ç", "ç"] },
    { base = "e", special = ["É", "é", "È", "è", "Ê", "ê"] },
    { base = "i", special = ["Î", "î", "Ï", "ï"] },
    { base = "o", special = ["Ô", "ô", "Œ", "œ"] },
    { base = "u", special = ["Ù", "ù", "Û", "û"] },
]